/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.11).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package udea.billing.api;

import org.springframework.web.bind.annotation.PathVariable;
import udea.billing.model.Bill;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@Api(value = "billing", description = "the billing API")
public interface BillingApi {

    @ApiOperation(value = "create a new billing", nickname = "newBill", notes = "create a new billing", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "bill created"),
        @ApiResponse(code = 400, message = "invalid input, object invalid") })
    @RequestMapping(value = "/billing",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Bill> newBill(@ApiParam(value = ""  )  @Valid @RequestBody Bill billing);

    @ApiOperation(value = "searches place", notes = "get places", response = String.class, responseContainer = "List", tags={  })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "all places", response = String.class),
            @ApiResponse(code = 400, message = "bad input parameter", response = String.class) })
    @RequestMapping(value = "/billing/{id}",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<String> getBilling(@PathVariable(value = "id") String id);

}
